version: '3.7'

services:
  #POSTGRESS
  postgress:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root

  # MYSQL
  database:
    container_name: mysql_db
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: rootuser
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql/:/var/lib/mysql/